const Menu = [
  {
    id: 1,
    image:'images/img1.jpg',
    name: 'Idli Sambhar',
    category:'breakfast',
    price:'₹25',
    description:'Lorem ipsum dolor sit amet orem ipsum dolor sit amet..',
  },
  {
    id: 2,
    image:'images/img2.jpg',
    name: 'Momos',
    category:'lunch', 
    price:'₹12',
    description:'Lorem ipsum dolor sit amet sit amet..',
  },
  {
    id: 3,
    image:'images/img3.jpg',
    name: 'Aloo Tikki',
    category:'dinner',
    price:'₹22',
    description:'Lorem amet orem ipsum dolor sit amet..',
  },
  {
    id: 4,
    image:'images/img1.jpg',
    name: 'Panjabi Thali',
    category:'lunch',
    price:'₹50',
    description:'Lorem orem ipsum dolor sit amet..',
  },
  {
    id: 5,
    image:'images/img3.jpg',
    name: 'Upma',
    category:'breakfast',
    price:'₹85',
    description:'Lorem orem ipsum dolor sit amet..',
  },
  {
    id: 6,
    image:'images/img1.jpg',
    name: 'Dhokla',
    category:'breakfast',
    price:'₹25',
    description:'Lorem ipsum dolor sit amet orem ipsum dolor sit amet..',
  },
  {
    id: 7,
    image:'images/img2.jpg',
    name: 'Momos',
    category:'lunch', 
    price:'₹12',
    description:'Lorem ipsum dolor sit amet sit amet..',
  },
  {
    id: 8,
    image:'images/img3.jpg',
    name: 'Aloo Tikki',
    category:'dinner',
    price:'₹22',
    description:'Lorem amet orem ipsum dolor sit amet..',
  },
  {
    id: 9,
    image:'images/img1.jpg',
    name: 'Upma',
    category:'lunch',
    price:'₹50',
    description:'Lorem orem ipsum dolor sit amet..',
  },
];

 export default Menu;